---
- name: Collect facts
  gather_facts: yes
  hosts: network
  #connection: local
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 60

  tasks:
    - ios_facts:
        gather_subset: "min"
       #provider: "{{ credentials }}"
        timeout: 20
      name: Collect IOS facts
      register: ios_facts

    - debug:
        msg: "{{ ansible_net_hostname }} File: {{ ansible_net_version }}"
