---
- name: Cisco config PE1
  hosts: edgep1
  connection: local
  vars:
   cli:
     username: admin
     password: 123
  tasks:
     - name: Configure OSPF
       ios_config:
          #provider: "{{ cli }}"
          parents: router ospf 100
          authorize: yes
          lines:
            - network 0.0.0.0 255.255.255.255 area 0
