---
- name: Provision L2VPN ETH2ETH for PE3
  gather_facts: no
  hosts: edgep3
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"

    vc_id: 34
    pseudowire_class: ETH-to-ETH
    ip_add: 10.255.255.14
    encapsulation: mpls
    int_name: GigabitEthernet3

  tasks:
    - name: Prepare Configuration
      ios_config:
         authorize: yes
         lines:
           - pseudowire-class {{ pseudowire_class }}
           - encapsulation {{ encapsulation }}
         match: exact

    - name: Create configure L2VPN
      ios_config:
         authorize: yes
         lines:
           - xconnect {{ ip_add}} {{ vc_id }} encapsulation {{ encapsulation }} pw-class {{ pseudowire_class }}
           - no shutdown
         parents: ['interface {{ int_name }}']
         match: exact
