---
- name: Provision MP-BGP for PE2
  gather_facts: no
  hosts: edgep2
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 200

    bgp_as_number: 64512
    ip_loopback: 10.255.255.11
   #mask_1: 255.225.255.252
    int_name: loopback0

  tasks:
   - name: Create configuration MP_BGP
     ios_config:
       authorize: yes
       parents: ['router bgp {{ bgp_as_number }}']
       lines:
         - address-family vpnv4
         - neighbor {{ ip_loopback }} activate
         - neighbor {{ ip_loopback }} send-community extended
         - exit-address-family
         - neighbor {{ ip_loopback }} remote-as {{ bgp_as_number }}
         - neighbor {{ ip_loopback }} update-source {{ int_name }}
         - address-family ipv4
         - neighbor {{ ip_loopback }} activate
         - exit-address-family
       match: exact
