---
- import_playbook: ospf_pe1.yaml
- import_playbook: ospf_pe2.yaml
- name: Provision Run show bgp
  gather_facts: no
  hosts: sjc
  connection: local
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 180
      
  tasks:
    - name: run show vrf, bgp remote devices
      ios_command:
        authorize: yes
        commands:
          - show bgp all
        provider: "{{ credentials }}"
      register: output

    - debug:
        msg: "{{ output.stdout_lines }}"    