---
- name: Provision OSPF for PE2
  gather_facts: no
  hosts: edgep2
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"

    bgp_as_number: 64512
    ospf_id: 2
    ospf_area: 'area 10'
    network_prefix: '10.255.11.0'
    wild_card_mask: '0.0.0.3'
    vrf_name: ONE

  tasks:
    - name: Create configure OSPF
      ios_config:
         authorize: yes
         lines:
           - redistribute bgp {{ bgp_as_number }} subnets
           - network {{ network_prefix }} {{ wild_card_mask }} {{ ospf_area }}
         parents: [' router ospf {{ ospf_id }} vrf {{ vrf_name }}']
         match: exact
    - name: Create redistribute OSPF on BGP
      ios_config:
         authorize: yes
         lines:
           - address-family ipv4 vrf {{ vrf_name }}
           - redistribute ospf {{ ospf_id }}
         parents: ['router bgp {{ bgp_as_number }}']
         match: exact
