---
- import_playbook: site_vrf_a.yaml
- import_playbook: site_vrf_b.yaml
- name: Provision show VRF 
  gather_facts: no
  hosts: sjc
  connection: local
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 180

  tasks:

    - name: Run 'show site VRF'
      ios_command:
        authorize: yes
        commands:
          - show vrf
        provider: "{{ credentials }}"
      register: output

    - debug:
        msg: "{{ output.stdout_lines }}"    