---
- name: Provision VRF ONE
  gather_facts: no
  hosts: edgep1
 #connection: local
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 180

  #  I decided to enter MPLS VPN variables directly into the Playbook.  There are other options of course
  #  These 5 variables are all that is needed to get a basic VRF enabled, add the RD and RT,
  #  apply the VRF to an interface of choice, and then add the address-family to BGP (could be other protocol)
    rd_id: '10.255.255.20:1'
    rt_imp: '10.255.255.20:1'
    rt_exp: '10.255.255.21:1'
    vrf_name: ONE
    int_name: GigabitEthernet4
    ip_add: '10.255.10.1 255.255.255.252'

  tasks:
    - name: Create VRF ONE
      ios_config:
        authorize: yes
        lines:
          - rd {{ rd_id }}
          - route-target export {{ rt_exp }}
          - route-target import {{ rt_imp }}
        parents: ['ip vrf {{ vrf_name }}']
        match: exact

    - name: Attach VRF ONE to Interface
      ios_config:
        authorize: yes
        lines:
          - ip vrf forwarding {{ vrf_name }}
          - no shutdown
          - ip address {{ ip_add }}
        parents: ['interface {{ int_name }}']
        match: exact
