- name: BUILD MPLS XML DATA
  template:
    src: mpls.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/mpls.xml"
- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/mpls.xml"
© 2020 GitHub, Inc.