- name: BUILD VRF XML DATA
  template:
    src: vrf_forwarding.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/vrf_forwarding.xml"
- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/vrf_forwarding.xml"
