---
interfaces:
  - type: GigabitEthernet
    name: 2
    description: connected to P4
    ipv4: 10.255.254.5
    ipv4_mask: 255.255.255.252
    mpls: true
    enabled: true
  - type: GigabitEthernet
    name: 3
    description: connected to P2
    ipv4: 10.255.254.1
    ipv4_mask: 255.255.255.252
    mpls: true
    enabled: true
  - type: GigabitEthernet
    name: 4
    description: connected to PE4
    ipv4: 10.255.254.37
    ipv4_mask: 255.255.255.252
    mpls: true
    enabled: true
  - type: GigabitEthernet
    name: 5
    description: connected to PE1
    ipv4: 10.255.254.9
    ipv4_mask: 255.255.255.252
    mpls: true
    enabled: true       
  - type: Loopback
    name: 0
    description: Loopback0
    ipv4: 10.255.255.1
    ipv4_mask: 255.255.255.255
    mpls: false


routing_core:
  - name: ospf
    id: 1
    router-id: 10.255.255.1
  - network: 
    ip: 10.255.254.0
    mask: 0.0.0.3
    area: 0
  - network: 
    ip: 10.255.254.4
    mask: 0.0.0.3
    area: 0
  - network: 
    ip: 10.255.254.8
    mask: 0.0.0.3
    area: 0
  - network: 
    ip: 10.255.254.36
    mask: 0.0.0.3
    area: 0    
  - network: 
    ip: 10.255.255.1
    mask: 0.0.0.3
    area: 0   