---
interfaces:
  - type: GigabitEthernet
    name: 2
    description: connected to P1
    ipv4: 10.255.254.2
    ipv4_mask: 255.255.255.252
    mpls: true
    enabled: true
  - type: GigabitEthernet
    name: 3
    description: connected to P3
    ipv4: 10.255.254.14
    ipv4_mask: 255.255.255.252
    mpls: true
    enabled: true
  - type: GigabitEthernet
    name: 4
    description: connected to PE1
    ipv4: 10.255.254.17
    ipv4_mask: 255.255.255.252
    mpls: true
    enabled: true
  - type: GigabitEthernet
    name: 5
    description: connected to PE3
    ipv4: 10.255.254.25
    ipv4_mask: 255.255.255.252
    mpls: true
    enabled: true   
  - type: GigabitEthernet
    name: 6
    description: connected to PE2
    ipv4: 10.255.254.21
    ipv4_mask: 255.255.255.252
    mpls: true
    enabled: true   
  - type: Loopback
    name: 0
    description: Loopback0
    ipv4: 10.255.255.2
    ipv4_mask: 255.255.255.255
    mpls: true


routing_core:
  - name: ospf
    id: 1
    router-id: 10.255.255.2
  - network: 
    ip: 10.255.254.0
    mask: 0.0.0.3
    area: 0
  - network: 
    ip: 10.255.254.12
    mask: 0.0.0.3
    area: 0
  - network: 
    ip: 10.255.254.16
    mask: 0.0.0.3
    area: 0
  - network: 
    ip: 10.255.254.20
    mask: 0.0.0.3
    area: 0    
  - network: 
    ip: 10.255.254.24
    mask: 0.0.0.3
    area: 0     
  - network: 
    ip: 10.255.255.2
    mask: 0.0.0.0
    area: 0     