---
interfaces:
  - type: GigabitEthernet
    name: 2
    description: connected to P1
    ipv4: 10.255.254.6
    ipv4_mask: 255.255.255.252
    mpls: true
    enabled: true
  - type: GigabitEthernet
    name: 3
    description: connected to P3
    ipv4: 10.255.254.34
    ipv4_mask: 255.255.255.252
    mpls: true
    enabled: true
  - type: GigabitEthernet
    name: 4
    description: connected to PE4
    ipv4: 10.255.254.41
    ipv4_mask: 255.255.255.252
    mpls: true
    enabled: true       
  - type: Loopback
    name: 0
    description: Loopback0
    ipv4: 10.255.255.4
    ipv4_mask: 255.255.255.255
    mpls: true


routing_core:
  - name: ospf
    id: 1
    router-id: 10.255.255.4
  - network: 
    ip: 10.255.254.32
    mask: 0.0.0.3
    area: 0
  - network: 
    ip: 10.255.254.40
    mask: 0.0.0.3
    area: 0
  - network: 
    ip: 10.255.254.4
    mask: 0.0.0.3
    area: 0    
  - network: 
    ip: 10.255.255.4
    mask: 0.0.0.3
    area: 0     